services:
  basex:
    container_name: basex
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    env_file:
      - path: "./.env.local"
        required: false
    environment:
      - PORT=${PORT}
      - ENVIRONTMENT=${ENVIRONTMENT}
